language: java
jdk:
  - oraclejdk8
sudo: required
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render"
  - sleep 3 # give xvfb some time to start
cache:
  directories:
  - $HOME/.m2
